#!/bin/bash

# MongoDB Atlas Setup Guide for QNOVA VR

echo "🗄️  MongoDB Atlas Setup Guide"
echo "================================"
echo ""
echo "1. Go to https://www.mongodb.com/atlas"
echo "2. Create account with email: qnovavr.de@gmail.com"
echo "3. Create new project: 'QNOVA VR Production'"
echo "4. Build database cluster:"
echo "   - Provider: AWS (recommended)"
echo "   - Region: Frankfurt (eu-central-1) - closest to Germany"
echo "   - Cluster Tier: M0 Sandbox (FREE)"
echo "   - Cluster Name: 'qnova-vr-cluster'"
echo ""
echo "5. Database Access:"
echo "   - Add database user: 'qnova_admin'"
echo "   - Generate secure password"
echo "   - Database User Privileges: Read and write to any database"
echo ""
echo "6. Network Access:"
echo "   - Add IP addresses: 0.0.0.0/0 (Allow access from anywhere)"
echo "   - Later restrict to your server IPs for security"
echo ""
echo "7. Get connection string:"
echo "   mongodb+srv://<username>:<password>@qnova-vr-cluster.xxxxx.mongodb.net/"
echo ""
echo "✅ MongoDB Atlas setup complete!"