#!/bin/bash

# Vercel Frontend Deployment Guide for QNOVA VR

echo "⚡ Vercel Frontend Deployment Guide"
echo "===================================="
echo ""
echo "1. Go to https://vercel.com"
echo "2. Sign up with GitHub account"
echo "3. Import your GitHub repository"
echo ""
echo "4. Project Configuration:"
echo "   - Framework Preset: Create React App"
echo "   - Root Directory: frontend"
echo "   - Build Command: yarn build"
echo "   - Output Directory: build"
echo ""
echo "5. Environment Variables (Add in Vercel dashboard):"
echo "   REACT_APP_BACKEND_URL=https://your-backend-url.up.railway.app"
echo ""
echo "6. Domain Configuration:"
echo "   - Vercel provides: qnova-vr.vercel.app"
echo "   - Add custom domain: qnova-vr.com"
echo "   - SSL certificate automatic"
echo ""
echo "7. Auto-deployments:"
echo "   - Production: Deploy from main branch"
echo "   - Preview: Deploy from pull requests"
echo ""
echo "8. Performance Features (Automatic):"
echo "   - Global CDN (100+ locations)"
echo "   - Image optimization"
echo "   - Static file compression"
echo "   - Edge caching"
echo ""
echo "✅ Website will be live at: https://qnova-vr.com"